#set( $symbol_dollar = '$' )
name: Release CI - Analysis
on:
  push:
    branches:
      - master
      - 'support/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${symbol_dollar}{{ runner.os }}-m2-${symbol_dollar}{{ hashFiles('**/pom.xml') }}
          restore-keys: ${symbol_dollar}{{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${symbol_dollar}{{ runner.os }}-sonar
          restore-keys: ${symbol_dollar}{{ runner.os }}-sonar
      - name: Verify
        run: mvn -B clean verify -Put,it,release -Dgpg.skip=true
      - name: Sonar analysis
        if: success()
        env:
          GITHUB_TOKEN: ${symbol_dollar}{{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${symbol_dollar}{{ secrets.SONAR_TOKEN }}
        run: mvn -B sonar:sonar
