#set( $symbol_dollar = '$' )
name: Release CI - Publish latest version site
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: github
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${symbol_dollar}{{ runner.os }}-m2-${symbol_dollar}{{ hashFiles('**/pom.xml') }}
          restore-keys: ${symbol_dollar}{{ runner.os }}-m2
      - name: Generate site
        run: |
          echo "Generating test site for latest release"
          mvn -B clean verify site site:stage -Put,it,release -Dgpg.skip=true
      - name: Publish site
        if: success()
        env:
          GITHUB_TOKEN: ${symbol_dollar}{{ secrets.GITHUB_TOKEN }}
        run: mvn -B scm-publish:publish-scm
