name: Publish latest release site CI
on:
  push:
    branches:
      - 'support/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate site
        run: mvn -B clean verify site site:stage -Put,it,release
      - name: Publish site
        if: success()
        run: mvn -B scm-publish:publish-scm -Dscmpublish.scm.branch=gh-pages -Dscmpublish.subDirectory=${github.ref#support/} -DserverId=github
